[package]
name = "bens_naive_rational_numbers"
version = "0.1.0"
authors = ["bcpeinhardt <benjaminpeinhardt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
